markdown: kramdown
permalink: /:title/
url: https://blog.amgod.net
name: Amgod Blog
author: Amgod
email: amgod20@qq.com
beian: None
weibo: 18850691
github: Amgod
giturl: amgod.github.io
safe: true
paginate: 20
about: "欢迎观赏、建议、拍砖……"
